# Generated by Django 3.2.7 on 2024-03-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
