# Generated by Django 5.0.1 on 2024-03-25 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0005_remove_stationprofile_station_incharge_name'),
        ('users_app', '0004_booking_booked_by_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_Date', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('reply', models.BooleanField(default=False)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station_app.station')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
