# Generated by Django 5.0.1 on 2024-03-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0002_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='station_latitude',
        ),
        migrations.RemoveField(
            model_name='station',
            name='station_longitude',
        ),
        migrations.AddField(
            model_name='station',
            name='slots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
