# Generated by Django 5.0.1 on 2024-03-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0003_remove_station_station_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationprofile',
            name='Station_incharge_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
