# Generated by Django 5.0.1 on 2024-03-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0004_stationprofile_station_incharge_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationprofile',
            name='Station_incharge_name',
        ),
    ]
